---
- name: Deploy FlexiBot to DigitalOcean
  hosts: flexibot
  become: true
  vars:
    ansible_command_timeout: 600

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker and dependencies
      apt:
        name:
          - docker.io
          - docker-compose
          - git
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create swap file
      command: fallocate -l 2G /swapfile
      args:
        creates: /swapfile

    - name: Set swap file permissions
      file:
        path: /swapfile
        mode: "0600"

    - name: Format swap file
      command: mkswap /swapfile
      args:
        creates: /swapfile

    - name: Enable swap
      command: swapon /swapfile
      ignore_errors: yes

    - name: Clone the project from GitHub
      git:
        repo: "https://github.com/kyawlinn-dev/flexibot.git"
        dest: /opt/flexibot
        force: yes

    - name: Copy backend .env to server
      copy:
        src: ../backend/.env
        dest: /opt/flexibot/backend/.env

    - name: Copy admin-dashboard .env to server
      copy:
        src: ../admin-dashboard/.env.local
        dest: /opt/flexibot/admin-dashboard/.env.local

    - name: Copy docker-compose.yml to server
      copy:
        src: ../docker-compose.yml
        dest: /opt/flexibot/docker-compose.yml

    - name: Copy gcloud credentials to server
      copy:
        src: ../backend/gcloud.json
        dest: /opt/flexibot/backend/gcloud.json
        mode: "0600"

    - name: Stop existing containers
      command: docker-compose down --remove-orphans
      args:
        chdir: /opt/flexibot
      ignore_errors: yes

    - name: Build and start containers
      command: docker-compose up -d --build
      args:
        chdir: /opt/flexibot
      timeout: 600